services:
  # Clock - interactive clock workspace with multiple time utilities
  clock:
    image: node:20-alpine
    container_name: clock
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules  # Anonymous volume for node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
