services:
  # Workspace Manager - serves at root domain
  workspace-manager:
    image: nginx:alpine
    container_name: workspace-manager
    volumes:
      - ./workspace-manager/public:/usr/share/nginx/html:ro
    networks:
      - traefik-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      
      # HTTP router for root domain
      - traefik.http.routers.workspace-manager.rule=Host(`${DOMAIN:-workspaces.etdofresh.com}`)
      - traefik.http.routers.workspace-manager.entrypoints=web
      - traefik.http.routers.workspace-manager.priority=1
      
      # HTTPS router for root domain
      - traefik.http.routers.workspace-manager-secure.rule=Host(`${DOMAIN:-workspaces.etdofresh.com}`)
      - traefik.http.routers.workspace-manager-secure.entrypoints=websecure
      - traefik.http.routers.workspace-manager-secure.tls=true
      - traefik.http.routers.workspace-manager-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.workspace-manager-secure.priority=1
      
      # Service configuration
      - traefik.http.services.workspace-manager.loadbalancer.server.port=80

networks:
  traefik-network:
    external: true