version: '3.8'

services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ./config/ddclient:/config
    restart: unless-stopped

# Note: After starting, edit /config/ddclient/ddclient.conf with your Namecheap settings