version: '3.8'
services:
  clock:
    container_name: workspace-clock
    networks:
      - traefik-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.routers.workspace-clock.rule=Host(`workspaces.etdofresh.com`) && PathPrefix(`/clock`)
      - traefik.http.routers.workspace-clock.entrypoints=web
      - traefik.http.routers.workspace-clock-secure.rule=Host(`workspaces.etdofresh.com`) && PathPrefix(`/clock`)
      - traefik.http.routers.workspace-clock-secure.entrypoints=websecure
      - traefik.http.routers.workspace-clock-secure.tls=true
      - traefik.http.routers.workspace-clock-secure.tls.certresolver=letsencrypt
      - traefik.http.middlewares.workspace-clock-strip.stripprefix.prefixes=/clock
      - traefik.http.routers.workspace-clock-secure.middlewares=workspace-clock-strip
      - traefik.http.services.workspace-clock.loadbalancer.server.port=3000
    environment:
      NODE_ENV: production
      PORT: 3000
      WORKSPACE_NAME: clock
    volumes:
      - .:/workspace:ro
    image: workspace-node-ephemeral:latest
    build:
      context: ./docker/node-ephemeral
      dockerfile: Dockerfile
    command:
      - npm
      - start
    healthcheck:
      test:
        - CMD
        - test
        - '-f'
        - /app/.container-ready
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
networks:
  traefik-network:
    external: true