version: '3.8'
services:
  investment:
    container_name: workspace-investment
    networks:
      - traefik-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.routers.workspace-investment.rule=Host(`workspaces.etdofresh.com`) && PathPrefix(`/investment`)
      - traefik.http.routers.workspace-investment.entrypoints=web
      - traefik.http.routers.workspace-investment-secure.rule=Host(`workspaces.etdofresh.com`) && PathPrefix(`/investment`)
      - traefik.http.routers.workspace-investment-secure.entrypoints=websecure
      - traefik.http.routers.workspace-investment-secure.tls=true
      - traefik.http.routers.workspace-investment-secure.tls.certresolver=letsencrypt
      - traefik.http.middlewares.workspace-investment-strip.stripprefix.prefixes=/investment
      - traefik.http.routers.workspace-investment-secure.middlewares=workspace-investment-strip
      - traefik.http.services.workspace-investment.loadbalancer.server.port=3000
    environment:
      NODE_ENV: production
      PORT: 3000
      WORKSPACE_NAME: investment
    volumes:
      - .:/workspace:ro
    image: workspace-node-ephemeral:latest
    build:
      context: ./docker/node-ephemeral
      dockerfile: Dockerfile
    command:
      - npm
      - run
      - dev
    healthcheck:
      test:
        - CMD
        - test
        - '-f'
        - /app/.container-ready
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
networks:
  traefik-network:
    external: true