version: '3.8'
services:
  www:
    container_name: workspace-www
    networks:
      - traefik-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.routers.workspace-www.rule=Host(`workspaces.etdofresh.com`)
      - traefik.http.routers.workspace-www.entrypoints=web
      - traefik.http.routers.workspace-www-secure.rule=Host(`workspaces.etdofresh.com`)
      - traefik.http.routers.workspace-www-secure.entrypoints=websecure
      - traefik.http.routers.workspace-www-secure.tls=true
      - traefik.http.routers.workspace-www-secure.tls.certresolver=letsencrypt
      - traefik.http.services.workspace-www.loadbalancer.server.port=3000
    environment:
      NODE_ENV: production
      PORT: 3000
      WORKSPACE_NAME: www
    volumes:
      - .:/workspace:ro
    image: workspace-node-ephemeral:latest
    build:
      context: ./docker/node-ephemeral
      dockerfile: Dockerfile
    command:
      - npm
      - start
    healthcheck:
      test:
        - CMD
        - test
        - '-f'
        - /app/.container-ready
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
networks:
  traefik-network:
    external: true