services:
  rclone-mount:
    image: rclone/rclone:latest
    container_name: rclone-mount
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    environment:
      RCLONE_CONFIG_MINIO_TYPE: s3
      RCLONE_CONFIG_MINIO_PROVIDER: Minio
      RCLONE_CONFIG_MINIO_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minioadmin}
      RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      RCLONE_CONFIG_MINIO_ENDPOINT: http://minio:9000
      RCLONE_CONFIG_MINIO_ENV_AUTH: "false"
    command: |
      mount minio:workspaces /workspaces
      --vfs-cache-mode writes
      --allow-other
      --allow-non-empty
      --log-level INFO
    volumes:
      # Mount the host's /workspaces directory to container's /workspaces
      - /workspaces:/workspaces:rshared
      - rclone_cache:/root/.cache/rclone
    restart: unless-stopped

volumes:
  rclone_cache:
