services:
  # Admin - workspace management interface at /admin with Vite hot reloading
  admin:
    image: node:20-alpine
    container_name: admin
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules  # Anonymous volume for node_modules
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker management
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    networks:
      - traefik-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      
      # Router for /admin (without slash) - redirects to /admin/
      - traefik.http.routers.admin-redirect.rule=Host(`${DOMAIN:-workspaces.etdofresh.com}`) && Path(`/admin`)
      - traefik.http.routers.admin-redirect.entrypoints=websecure
      - traefik.http.routers.admin-redirect.tls=true
      - traefik.http.routers.admin-redirect.tls.certresolver=letsencrypt
      - traefik.http.routers.admin-redirect.priority=20
      - traefik.http.routers.admin-redirect.middlewares=admin-slash
      
      # Main router for /admin/ path
      - traefik.http.routers.admin.rule=Host(`${DOMAIN:-workspaces.etdofresh.com}`) && PathPrefix(`/admin/`)
      - traefik.http.routers.admin.entrypoints=websecure
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.tls.certresolver=letsencrypt
      - traefik.http.routers.admin.priority=10
      - traefik.http.routers.admin.middlewares=admin-stripprefix
      
      # Add trailing slash
      - traefik.http.middlewares.admin-slash.redirectregex.regex=^(.*)$$
      - traefik.http.middlewares.admin-slash.redirectregex.replacement=$${1}/
      - traefik.http.middlewares.admin-slash.redirectregex.permanent=true
      
      # Strip /admin prefix so Vite serves from its base path
      - traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/admin
      
      # Service configuration - Vite runs on default port 5173
      - traefik.http.services.admin.loadbalancer.server.port=5173

networks:
  traefik-network:
    external: true