services:
  file-browser:
    image: node:20-alpine
    container_name: file-browser
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules  # Anonymous volume to prevent conflicts
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - DOMAIN=workspaces.etdofresh.com
    restart: unless-stopped
