version: '3.8'
services:
  public:
    container_name: workspace-public
    networks:
      - traefik-network
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.docker.network=traefik-network"'
      - '"traefik.http.routers.workspace-public.rule=Host(`etdofresh-dev.duckdns.org`) && PathPrefix(`/public`)"'
      - '"traefik.http.routers.workspace-public.entrypoints=web"'
      - '"traefik.http.routers.workspace-public-secure.rule=Host(`etdofresh-dev.duckdns.org`) && PathPrefix(`/public`)"'
      - '"traefik.http.routers.workspace-public-secure.entrypoints=websecure"'
      - '"traefik.http.routers.workspace-public-secure.tls=true"'
      - '"traefik.http.routers.workspace-public-secure.tls.certresolver=letsencrypt"'
      - '"traefik.http.middlewares.workspace-public-strip.stripprefix.prefixes=/public"'
      - '"traefik.http.routers.workspace-public-secure.middlewares=workspace-public-strip"'
      - '"traefik.http.services.workspace-public.loadbalancer.server.port=3000"'
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app:ro
    command: sh -c "npm install -g http-server && http-server -p 3000 --cors -c-1"
networks:
  traefik-network:
    external: true
