services:
  minio:
    image: minio/minio:latest
    container_name: minio
    # No ports exposed - access via external configuration
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_DOMAIN: ${DOMAIN:-workspaces.etdofresh.com}
      # Set URLs for HTTPS access through Traefik
      MINIO_BROWSER_REDIRECT_URL: https://${DOMAIN:-workspaces.etdofresh.com}:9001
      MINIO_SERVER_URL: https://${DOMAIN:-workspaces.etdofresh.com}:9000
      # Allow CORS for browser access
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - minio_data:/data
    command: server /data --console-address "0.0.0.0:9001" --address "0.0.0.0:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

volumes:
  minio_data:
    external: true
    name: cloudyknight_minio_data
