services:
  multi-pane-browser:
    image: node:20-alpine
    container_name: multi-pane-browser
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
