services:
  # Admin - workspace management interface at /admin with Vite hot reloading
  admin:
    image: node:20-alpine
    container_name: admin
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules  # Anonymous volume for node_modules
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker management
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
